### ISSUE TITLE
Compatible with Chrome devtools?

### ISSUE THREAD

**Issue by danbastin** [adambutler/vuejs-rails#22]
Is there a way to get this gem to work with the devtools chrome extension or will I just need to manually include Vue for that to work?

**Comment by adambutler** [comment]
It doesn't seem like [vue-devtools](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd/related) depends on any special dev build so I can see no reason as to why this would not be compatible.

What if any problems are you experiencing?

**Comment by danbastin** [comment]
The Vue tab in my devtools does not appear. It's seems the most common reason for this is that a minified version of Vue is being used. I'm not terribly familiar with the behind the scenes of gems and the asset pipeline. It appears to me you have the unminified version here, but I thought maybe rails was minifying it automatically causing the devtools plugin to not recognize it? I'm probably way off on that though.

**Comment by danbastin** [comment]
Just noticed that restriction was changed. This may be an issue for the devtools devs. Feel free to close this if you find that is likely the case.

**Comment by marshallshen** [comment]
@danbastin I am going close this for now. Let me know if this is still an issue we should look into.
