### ISSUE TITLE
Debugging cofiguration

### ISSUE THREAD

**Issue by LeKristapino** [adambutler/vuejs-rails#37]
Hi, thanks for the wrapper gem. Would it be possible to create configuration variable and include the production version of Vue library, so people can configure environments, where they want Vue debugging turned off?

**Comment by lackneets** [comment]
+1

**Comment by sterrym** [comment]
👍

**Comment by ckimdev** [comment]
+1

**Comment by YurySolovyov** [comment]
@adambutler will you accept a PR implementing it?

**Comment by adambutler** [comment]
👍  Sure
