### ISSUE TITLE
Unable to load development version

### ISSUE THREAD

**Issue by emersonthis** [adambutler/vuejs-rails#41]
I followed the documentation for enabling development mode, but I'm still getting the min version of the script, which prevents the Vue DevTools from working.

Gemfile
```
gem 'rails', '~> 5.0.1'
gem "sprockets"
gem "sprockets-es6"
gem 'babel-transpiler'
gem 'vuejs-rails' #2.3.2
```

application.js
`//= require vue`

config/initializers/vue_config.rb
`Vue.development_mode = true`

What am I doing wrong?

**Comment by adambutler** [comment]
Doh! Let me try and help, first can we rule the most obvious thing out... Have you restarted your server? Since the flag is in an initializer it will only take effect at the server initialisation.

**Comment by emersonthis** [comment]
Bingo! I was not restarting the server. I thought that `rake tmp:cache:clear` was sufficient. For whatever it's worth, I had to restart the server, then run `rake tmp:cache:clear`, then restart the server again for it to kick in. Thanks for your help!
